version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
  nodeapp:
    build: 
      context: ./backend
      args:
        NODE_ENV: development
    volumes:
      - ./backend:/app
    ports: # use if it is necessary to expose the container to the host machine
      - "3000:3000"
      - "3001:3001"
    command: [ "npm", "run", "start" ]
